# Generated by Django 5.1.6 on 2025-03-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='title',
        ),
    ]
